module ContentType

let toExtension = function
    | "audio/aac" -> ".AAC"
    | "audio/aiff" -> ".aiff"
    | "audio/basic" -> ".snd"
    | "audio/mid" -> ".midi"
    | "audio/mp4" -> ".m4a"
    | "audio/mpeg" -> ".mp3"
    | "audio/wav" -> ".wav"
    | "audio/x-m4a" -> ".m4a"
    | "audio/x-mpegurl" -> ".m3u"
    | "audio/x-pn-realaudio" -> ".ra"
    | "audio/x-smd" -> ".smd"
    | "video/3gpp" -> ".3gp"
    | "video/3gpp2" -> ".3gp2"
    | "video/mp4" -> ".mp4"
    | "video/mpeg" -> ".mpg"
    | "video/quicktime" -> ".mov"
    | "video/vnd.dlna.mpeg-tts" -> ".m2t"
    | "video/x-dv" -> ".dv"
    | "video/x-la-asf" -> ".lsf"
    | "video/x-ms-asf" -> ".asf"
    | x -> failwith $"MIME type of {x} not included in function converting to the file extension."